#!/bin/bash

if [ ! -d "/ci-eye" ];then
    echo "No /ci-eye folder found for config. Please docker run -d -v /your/ci-eye/config:/ci-eye bobtfish/cieye" >&2
    exit 1
fi

exec /usr/bin/java -jar /usr/share/ci-eye-0.4.0.jar 47819

