#!/bin/bash

if [ ! -d "/ci-eye" ];then
    echo "No /ci-eye folder found for config. Please docker run -d -v /your/ci-eye/config:/ci-eye bobtfish/cieye" >&2
    exit 1
fi

if [ ! -f "/ci-eye/views.txt" ];then
    cp -r /example-config/* /ci-eye/
fi

if [ ! -d "/ci-eye/logs" ];then
    mkdir /ci-eye/logs
fi
chown nobody:nobody /ci-eye/logs

exec setuidgid nobody /usr/bin/java -jar /usr/share/ci-eye-0.4.0.jar 47819

